"""empty message

Revision ID: 22af23dcf0d3
Revises:
Create Date: 2025-07-14 17:25:35.420624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22af23dcf0d3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    op.drop_table("users")
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "users",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("pwhash", sa.VARCHAR(length=60), nullable=False),
        sa.Column("salt", sa.VARCHAR(length=29), nullable=False),
        sa.Column("user_id", sa.CHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("user_id"),
    )
    _ = op.create_table(
        "rooms",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("video_source", sa.VARCHAR(length=7), nullable=False),
        sa.Column("video_source_data", sa.VARCHAR(length=256), nullable=False),
        sa.Column("img_link", sa.VARCHAR(length=256), nullable=False),
        sa.Column("room_id", sa.CHAR(length=32), nullable=False),
        sa.Column("last_file_ind", sa.INTEGER(), nullable=False),
        sa.Column("last_watch_ts", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("room_id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###
