"""empty message

Revision ID: a6bf158341bd
Revises:
Create Date: 2025-07-14 17:51:15.883997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6bf158341bd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column(
            "video_source",
            sa.Enum("torrent", "link", name="videosourcesenum"),
            nullable=False,
        ),
        sa.Column("video_source_data", sa.String(length=256), nullable=False),
        sa.Column("img_link", sa.String(length=256), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("last_file_ind", sa.Integer(), nullable=False),
        sa.Column("last_watch_ts", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("room_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("pwhash", sa.String(length=60), nullable=False),
        sa.Column("salt", sa.String(length=29), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("rooms")
    # ### end Alembic commands ###
